SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

TRUNCATE Table own_funcesp.PRE_TBL_TempExtrat_ctb;
			   

BEGIN
	OWN_FUNCESP.PRE_PRC_EXTRATOCALCULA(40,'PSAP/Eletropaulo',TO_DATE('31/03/2020','DD/MM/YYYY'));
	OWN_FUNCESP.PROC_REND_ESTIM(40,'PSAP/Eletropaulo',TO_DATE('31/03/2020','DD/MM/YYYY'));
	--
	OWN_FUNCESP.PRE_PRC_EXTRATOCALCULA(40,'PSAP/Eletropaulo',TO_DATE('31/05/2020','DD/MM/YYYY'));
	OWN_FUNCESP.PROC_REND_ESTIM(40,'PSAP/Eletropaulo',TO_DATE('31/05/2020','DD/MM/YYYY'));
	--
	OWN_FUNCESP.PRE_PRC_EXTRATOCALCULA(40,'PSAP/Eletropaulo',TO_DATE('30/06/2020','DD/MM/YYYY'));
	OWN_FUNCESP.PROC_REND_ESTIM(40,'PSAP/Eletropaulo',TO_DATE('30/06/2020','DD/MM/YYYY'));
END;


	


  