SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

/*Projeto criado para a PSD-11865 - Ajustes no extrato previdenciário para atender o saldamento PSAP
  Autor: Adriano Lima
  Data: 11/11/2020
  Calcula os campos: RENDA_ESTIM_PROP e RENDA_ESTIM_INT
*/ 

CREATE OR REPLACE PROCEDURE OWN_FUNCESP.PROC_REND_ESTIM AS

BEGIN

    DECLARE
    
    L_COD_EMPRS ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.COD_EMPRS%TYPE:= 40;
    L_DCR_PLANO ATT.FC_PRE_TBL_BASE_EXTRAT_CTB.DCR_PLANO%TYPE:= 'PSAP/Eletropaulo';
    

      CURSOR CUR_DU_DV IS

     SELECT  NVL(SUM(VLR_BENEF_PSAP_PROP + VLR_BENEF_BD_PROP + VLR_BENEF_CV_PROP),0)  AS RENDA_ESTIM_PROP
            ,NVL(SUM(VLR_BENEF_PSAP_INTE + VLR_BENEF_BD_INTE + VLR_BENEF_CV_INTE),0)  AS RENDA_ESTIM_INT
            ,FPTB.DCR_PLANO
            ,FPTB.NUM_RGTRO_EMPRG
        FROM ATT.FC_PRE_TBL_BASE_EXTRAT_CTB  FPTB  -- OFICIAL
         WHERE FPTB.COD_EMPRS       = L_COD_EMPRS
         AND   FPTB.DCR_PLANO       = L_DCR_PLANO      
         --AND   FPTB.NUM_RGTRO_EMPRG = '0002014424-9'
         GROUP BY FPTB.DCR_PLANO, FPTB.NUM_RGTRO_EMPRG;   



      V_CUR_DU_DV CUR_DU_DV%ROWTYPE;


    BEGIN
      OPEN CUR_DU_DV;
           LOOP
             FETCH CUR_DU_DV INTO V_CUR_DU_DV;
             EXIT WHEN CUR_DU_DV%NOTFOUND;


             UPDATE ATT.FC_PRE_TBL_BASE_EXTRAT_CTB
             SET RENDA_ESTIM_PROP  = V_CUR_DU_DV.RENDA_ESTIM_PROP, RENDA_ESTIM_INT = V_CUR_DU_DV.RENDA_ESTIM_INT
             WHERE 				  0=0
             AND   DCR_PLANO       = V_CUR_DU_DV.DCR_PLANO
             AND   NUM_RGTRO_EMPRG = V_CUR_DU_DV.NUM_RGTRO_EMPRG;
             
           END LOOP;
      CLOSE CUR_DU_DV;
		COMMIT;
          EXCEPTION

        WHEN OTHERS THEN
               DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO: '||SQLCODE||' MSG: '||SQLERRM);
               DBMS_OUTPUT.PUT_LINE('LINHA: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);

    END;

END;
