SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;


GRANT SELECT,UPDATE ON ATT.FC_PRE_TBL_BASE_EXTRAT_CTB TO OWN_FUNCESP;
-- GRANT SELECT,UPDATE, INSERT, DELETE ON OWN_FUNCESP. TO OWN_FUNCESP;
GRANT SELECT ON ATT.HIST_VALOR_BNF TO OWN_FUNCESP;
GRANT SELECT ON ATT.SLD_CONTA_PARTIC_FSS TO OWN_FUNCESP;
GRANT SELECT ON ATT.CONTA_FSS TO OWN_FUNCESP;
GRANT SELECT ON ATT.COTACAO_DIA_UM TO OWN_FUNCESP;
-- GRANT EXECUTE ON OWN_FUNCESP.PRE_PRC_EXTRATOCALCULA TO OWN_FUNCESP;
-- GRANT EXECUTE ON OWN_FUNCESP.PRE_PRC_EXTRATOATUALIZA TO OWN_FUNCESP;

GRANT EXECUTE ON ATT.FCESP_VLR_CTB_ASSIST TO OWN_FUNCESP;

