SET ECHO ON
SET TIME ON
SET TIMING ON
SET SQLBL ON
SET SERVEROUTPUT ON SIZE 1000000
SHOW USER
SELECT * FROM GLOBAL_NAME;
SELECT INSTANCE_NAME, HOST_NAME FROM V$INSTANCE;
SELECT TO_CHAR(SYSDATE,'DD/MM/YYYY HH24:MI:SS') DATA FROM DUAL;

/*Projeto criado para a PSD-11865 - Ajustes no extrato previdenciário para atender o saldamento PSAP
  Autor: Adriano Lima
  Data: 12/11/2020
  Calcula os campos: RENDA_ESTIM_PROP e RENDA_ESTIM_INT
*/ 


CREATE INDEX ATT.FC_PRE_IDX_BASE_EXTRAT_CTB_01 ON ATT.FC_PRE_TBL_BASE_EXTRAT_CTB(DTA_FIM_EXTR)
tablespace TS_ATT_IX_01;
